title: "Kevin Armstrong II"
description: "University of California, Berkeley<br>Mechanical Engineering ’28 | Dean’s List<br>Student-Athlete, Men’s Basketball"
logo: /assets/img/Headshot_Circle.png
show_downloads: false
theme: jekyll-theme-minimal
